spring:
  application:
    name: jobsearcher
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

tavily:
  api-key: ${TAVILY_API_KEY}



