spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
    vectorstore:
      pgvector:
        initialize-schema: true

  jpa:
    hibernate:
      ddl-auto: update

otlm:
  base-url: http://host.docker.internal:8082

logging:
  level:
    org:
      apache:
        pdfbox:
          pdmodel:
            font:
              FileSystemFontProvider: ERROR
      springframework:
        ai:
          chat:
            client:
              advisor:
                SimpleLoggerAdvisor: INFO